
filler_words = ['hmmm', 'ehhhh', 'tsk', 'mmkay', 'ahhh', 'uhh', 'meh', 'pffft', 'bleh', 'psst', 'huh-uh','nuh-uh', 'heh','wahey',
                    'well, you see', 'I mean, I guess', 'frankly', 'anyways', 'basically', 'as a matter of fact', 'apparently', 'especially', 'fundamentally', 'moreover',
                    'nonetheless', 'otherwise','like','well','really','just','anyhow', 'I mean to say', 'like I said','by the way','at the end of the day', 'I think',
                    'I suppose','I guess','in a way','kind of','sort of','you know', 'oops','ahem','huh','oh','tsk-tsk','mm-hmm','eh','mmm', 
                    'seemingly', 'nevertheless', 'similarly', 'Actually', 'Honestly','sure', 'Right', 'OK', 'I mean', 'In any case', 'As I was saying', 'To be honest',
                    'in other words', 'to some extent', 'needless to say', 'in a sense', 'all things considered', 'on the other hand', 'for instance', 'that being said',
                     'fundamentally	to a certain extent', 'as it were', 'that said', 'as a result', 'at any rate', 'be that as it may', 'truth be told' ]
    

inclusive_word = {'the poor low-class people poor people': ['people whose incomes are below','the federal poverty threshold',
                 'people whose self-reported incomes','were in the lowest income bracket'],               
                '“long time no see” or “no can do': ['“it’s been a while!” and “sorry',
                'i can’t'],
                'person who is hearing impaired': ['hard-of-hearing person',
                'person who is hard-of-hearing'],
                'people who have special needs': ['people who have particular requirements',
                'people who require specific  accommodations'],
                '“sold down the river”_x000d_': ['betrayed'],
                'sex with an underage person': ['child who has been trafficked',
                'child who has been raped',
                'rape'],
                'visually challenged person': ['visually impaired person',
                'vision-impaired person',
                'person who is visually impaired',
                'person who is vision impaired'],
                'hearing-impaired person': ['hard-of-hearing person',
                'person who is hard-of-hearing'],
                'sight-challenged person': ['visually impaired person',
                'vision-impaired person',
                'person who is visually impaired',
                'person who is vision impaired'],
                'wheelchair-bound person': ['wheelchair user', 'person in a wheelchair'],
                'go off the reservation': ['disagree with the group',
                'defect from the group'],
                'physically challenged': ['person with a disability',
                'person with a physical disability',
                'people with intellectual disabilities'],
                '“i look like a tramp”': ['i look messy', 'untidy”'],
                'abusive relationship': ['relationship with a person who is abusive'],
                'person with deafness': ['deaf person'],
                'best man for the job': ['best person for the job'],
                'poor women and girls': ['women and girls living', 'in poverty'],
                'unsuccessful suicide': ['took their own life',
                'ended their own life',
                'death by suicide',
                'completed suicide',
                'attempted suicide'],
                'mentally challenged': ['person with a disability',
                'person with a physical disability',
                'people with intellectual disabilities'],
                'class of the person': ['socioeconomic status'],
                'take your best shot': ['give it a go /try'],
                'person who is deaf': ['deaf person'],
                'the burden of care': ['care workload', 'heavy and unequal care work'],
                'is afflicted with': ['is affected by'],
                'mentally retarded': ['person with a disability',
                'person with a physical disability',
                'people with intellectual disabilities'],
                'gender minorities': ['gender non-conforming people (gnc)'],
                'people struggling': ['people facing barriers'],
                'nonconsensual sex': ['child who has been trafficked',
                'child who has been raped',
                'rape'],
                'sanitary products': ['menstrual products', 'period products'],
                'expectant mothers': ['pregnant women', 'people who become', 'pregnant'],
                'illegal immigrant': ['asylum seeker', 'person/people seeking asylum'],
                'natural disasters': ['natural shocks',
                'neoliberalismnatural hazards',
                'human disasters'],
                'wheelchair-bound': ['mobility impaired',
                'person with a physical',
                'impairment'],
                'african american': ['black person'],
                'tribal knowledge': ['institute/ background knowledge'],
                'female scientist': ['scientist'],
                'domestic servant': ['domestic workers'],
                'pull the trigger': ['give it a go /try'],
                'child prostitute': ['child who has been trafficked',
                'child who has been raped',
                'rape'],
                'feminine hygiene': ['menstrual products', 'period products'],
                'economic migrant': ['migrant'],
                'homeless person': ['person without housing'],
                'senior citizens': ['older adults',
                'older people',
                'persons 65 years and older',
                'the older population'],
                'disabled people': ['people with a disability/disabilities'],
                'the handicapped': ['people with a disability/disabilities'],
                'minority groups': ['lgbtqia+  groups'],
                '“to get gypped”': ['to get ripped off'],
                'is a victim of': ['is affected by'],
                'elderly people': ['older adults',
                'older people',
                'persons 65 years and older',
                'the older population'],
                'mental patient': ['person with mental disorder'],
                'peanut gallery': ['outside opinions'],
                'child marriage': ['forced marriage'],
                'early marriage': ['forced marriage'],
                'take a shot at': ['give it a go /try'],
                'take a stab at': ['give it a go /try'],
                'special needs': ['person with a disability',
                'person with a physical disability',
                'people with intellectual disabilities'],
                'brain damaged': ['person with a traumatic brain injury'],
                'standing with': ['in solidarity with'],
                'spirit animal': ['favorite animal', 'animal i would most like to be'],
                'suffers from': ['is affected by'],
                'mentally ill': ['person living with a mental health condition\nperson with a mental disorder\nperson with a mental illness'],
                'the disabled': ['people with a disability/disabilities'],
                'black market': ['informal economy'],
                'the homeless': ['homeless people',
                'homeless person',
                'people experiencing',
                'homelessness'],
                'labour force': ['paid labour', 'paid \nlabour force'],
                'to get jewed': ['to get haggled down'],
                'the elderly': ['older adults',
                'older people',
                'persons 65 years and older',
                'the older population'],
                'aids victim': ['person with aids'],
                'meth addict': ['person with substance use disorder'],
                'born a girl': ['assigned female at birth (afab)'],
                'born female': ['assigned female at birth (afab)'],
                'care burden': ['care workload', 'heavy and unequal care work'],
                'decent work': ['dignified work'],
                'prostitute': ['person who engages in sex work'],
                'foreigners': ['people from overseas'],
                'white list': ['allow list'],
                'mixed race': ['biracial', 'multiracial'],
                'saleswoman': ['salesperson', 'sales representative'],
                'born a boy': ['assigned male at birth (amab)'],
                'girlfriend': ['partner'],
                'killing it': ['great job!', 'awesome!'],
                'alcoholic': ['person with alcohol use disorder'],
                'blindspot': ['missed opportunity'],
                'blacklist': ['deny list'],
                'birth sex': ['assigned sex', 'sex assigned at birth'],
                'natal sex': ['assigned sex', 'sex assigned at birth'],
                'born male': ['assigned male at birth (amab)'],
                'boyfriend': ['partner'],
                'spokesman': ['spokesperson'],
                'survivor': ['person who has experienced', 'person who has been impacted by'],
                'prisoner': ['person who is/has been incarcerated'],
                'the aged': ['older adults',
                'older people',
                'persons 65 years and older',
                'the older population'],
                'crippled': ['mobility impaired', 'person with a physical', 'impairment'],
                'dwarfism': ['person with short',
                'stature',
                'person with',
                'restricted growth'],
                'salesman': ['salesperson', 'sales representative'],
                'pro-life': ['anti-abortion', 'anti-choice'],
                'chairman': ['chair/chairperson'],
                'pipeline': ['pathway'],
                'convict': ['person who is/has been incarcerated'],
                'husband': ['spouses'],
                'mankind': ['human beings', 'humankind'],
                'peasant': ['smallholder',
                'smallholder farmer',
                'agricultural labourer',
                'subsistence farmer'],
                'victim': ['person who has experienced', 'person who has been impacted by'],
                'addict': ['person with a substance use disorder'],
                'man up': ['be brave'],
                'mother': ['parent', 'parenthood'],
                'father': ['parent', 'parenthood'],
                'nephew': ['nibling'],
                'powwow': ['meeting', 'party', 'or gathering'],
                'dwarf': ['person with short', 'stature', 'person with', 'restricted growth'],
                'asian': ['asian american', 'asian canadian respectively'],
                'bipoc': ['“people/persons of color” and “communities of color'],
                'woman': ['person/ individual'],
                'niece': ['nibling'],
                'tribe': ['friends', 'group', 'pals', 'team'],
                'expat': ['migrant'],
                'guru': ['expert/ guide'],
                'wife': ['spouses'],
                'vawg': ['violence against', 'women and girls'],
                'ocd': ['person with ocd'],
                'man': ['person/ individual']}
                    
                